# -*- coding: utf-8 -*-
"""Brain_Tumor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MkhmKlmCzxMoD2dczSyVcXcCfRdryViB

# **Load and Pre-processing the Dataset**
"""

import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Paths to datasets in Google Drive
test_path  = "/content/drive/MyDrive/brain_tumor/brain_tumor_dataset/Testing"
train_path = "/content/drive/MyDrive/brain_tumor/brain_tumor_dataset/Training"

output_base  = "/content/drive/MyDrive/processed_data"
output_train = os.path.join(output_base, "train")
output_test  = os.path.join(output_base, "test")

os.makedirs(output_train, exist_ok=True)
os.makedirs(output_test, exist_ok=True)

IMG_SIZE = 224

# Improved Image Processing (No Rotation Correction)
def process_image(img_path, save_path, show=False):
    img = cv2.imread(img_path)

    if show:
        plt.figure(figsize=(10,4))
        plt.subplot(1,3,1)
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        plt.title('Original')
        plt.axis('off')

    # 1) Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 2) CLAHE first (Enhance local contrast)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    clahe_img = clahe.apply(gray)

    # 3) Gaussian Blur to reduce noise
    blur = cv2.GaussianBlur(clahe_img, (3,3), 0)

    # 4) Convert to float32
    blur = blur.astype("float32")

    # 5) Resize
    resized = cv2.resize(blur, (IMG_SIZE, IMG_SIZE))

    # 6) Normalize 0–1 for model input
    final_norm = resized / 255.0

    # Save processed image as uint8 for visualization
    save_img = (final_norm * 255).astype(np.uint8)
    cv2.imwrite(save_path, save_img)

    if show:
        plt.subplot(1,3,2)
        plt.imshow(clahe_img, cmap='gray')
        plt.title('CLAHE')
        plt.axis('off')

        plt.subplot(1,3,3)
        plt.imshow(save_img, cmap='gray')
        plt.title('Final Processed')
        plt.axis('off')
        plt.show()

    return final_norm

# Process all images in a folder
def process_folder(input_folder, output_folder, show_first_image=False):
    first_image_shown = False
    for subfolder in os.listdir(input_folder):
        subfolder_path = os.path.join(input_folder, subfolder)
        if not os.path.isdir(subfolder_path):
            continue

        output_subfolder = os.path.join(output_folder, subfolder)
        os.makedirs(output_subfolder, exist_ok=True)

        for filename in os.listdir(subfolder_path):
            if filename.lower().endswith(('.jpg', '.jpeg', '.png')):
                img_path = os.path.join(subfolder_path, filename)
                save_path = os.path.join(output_subfolder, filename)

                show = show_first_image and not first_image_shown
                process_image(img_path, save_path, show)
                if show:
                    first_image_shown = True

print("Processing Train Dataset...")
process_folder(train_path, output_train, show_first_image=True)

print("Processing Test Dataset...")
process_folder(test_path, output_test, show_first_image=False)

print("Processing Done!")

import random
import matplotlib.pyplot as plt
import cv2

def show_random_images(path, num=5):
    classes = os.listdir(path)

    for cls in classes:
        cls_path = os.path.join(path, cls)
        if not os.path.isdir(cls_path):
            continue

        images = os.listdir(cls_path)
        random_imgs = random.sample(images, min(num, len(images)))

        print(f"Showing samples from class: {cls}")

        plt.figure(figsize=(10,2))
        for i, img_name in enumerate(random_imgs):
            img_path = os.path.join(cls_path, img_name)
            img = cv2.imread(img_path)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            plt.subplot(1, num, i+1)
            plt.imshow(img)
            plt.axis("off")
        plt.show()

show_random_images(train_path, num=5)

def dataset_balance(path):
    classes = os.listdir(path)
    counts = {}

    for cls in classes:
        cls_path = os.path.join(path, cls)
        if os.path.isdir(cls_path):
            counts[cls] = len(os.listdir(cls_path))

    print(counts)

    plt.bar(counts.keys(), counts.values())
    plt.title("Dataset Class Distribution")
    plt.xticks(rotation=45)
    plt.show()

dataset_balance(train_path)

output_base  = "/content/drive/MyDrive/processed_data"
output_train = os.path.join(output_base, "train")
output_test  = os.path.join(output_base, "test")

"""# **Import Resources**"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping

"""# **Explore the Data**"""

image_extensions = ('.jpg', '.jpeg', '.png')
total_images = 0

for root, dirs, files in os.walk(output_base):
    for file in files:
        if file.lower().endswith(image_extensions):
            total_images += 1

print(f"\n The total number of images {total_images}")

IMG_SIZE = 224
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.15,
    shear_range=0.15,
    brightness_range=[0.8,1.2],
    horizontal_flip=True,
    vertical_flip=True
)

test_datagen = ImageDataGenerator()


# Download data directly
train_data = train_datagen.flow_from_directory(
    output_train,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    color_mode='grayscale',
    shuffle=True
)

test_data = test_datagen.flow_from_directory(
    output_test,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    color_mode='grayscale',
    shuffle=False
)

print(f"Downloaded {train_data.samples} training image")
print(f"Downloaded {test_data.samples} testing image")

# Create CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(IMG_SIZE, IMG_SIZE, 1)),

    # Convolutional layers
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(2,2),

    # Flatten
    tf.keras.layers.Flatten(),

    # Dense layers
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.5),

    # Output layer
    tf.keras.layers.Dense(train_data.num_classes, activation='softmax')
])


# View form summary
model.summary()

# Assemble the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)


# Train the Model
history = model.fit(
    train_data,
    epochs=30,
    callbacks=[early_stop],
    verbose=1
)

#Evaluate on full test set

loss, acc = model.evaluate(test_data)
print(f"\nFinal test accuracy: {acc*100:.2f}%")
print(f"loss : {loss:.4f}")

# Confusion matrix for test data
import numpy as np
from sklearn.metrics import confusion_matrix
import seaborn as sns

# Prediction on all test images
y_pred = model.predict(test_data, verbose=0)
y_pred_classes = np.argmax(y_pred, axis=1)

# Obtaining genuine labels
y_true = test_data.classes

# Calculating the confusion matrix
cm = confusion_matrix(y_true, y_pred_classes)

# plot
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=list(test_data.class_indices.keys()),
            yticklabels=list(test_data.class_indices.keys()))

plt.title('Confusion Matrix', fontsize=16, pad=20)
plt.ylabel('real classification', fontsize=12)
plt.xlabel('Expected rating', fontsize=12)
plt.show()

# Calculating the accuracy from the matrix
correct_predictions = np.trace(cm)  # Total main diameter
total_predictions = np.sum(cm)
accuracy = correct_predictions / total_predictions * 100

print(f"Accuracy from the confusion matrix: {accuracy:.1f}%")
print(f"Total ratings: {total_predictions}")

import random

cls = random.choice(os.listdir(output_test))
img_name = random.choice(os.listdir(os.path.join(output_test, cls)))
img_path = os.path.join(output_test, cls, img_name)

img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
img_resized = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
img_norm = img_resized / 255.0
img_input = np.expand_dims(img_norm, axis=(0,-1))

pred = model.predict(img_input)[0]
pred_class = np.argmax(pred)

print("Real image : ", cls)
print("predict image : ", list(test_data.class_indices.keys())[pred_class])